# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_progressbar_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(120, 417)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_progressbar = QtWidgets.QFrame(Form)
        self.frame_progressbar.setMinimumSize(QtCore.QSize(101, 0))
        self.frame_progressbar.setMaximumSize(QtCore.QSize(101, 16777215))
        self.frame_progressbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_progressbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_progressbar.setObjectName("frame_progressbar")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_progressbar)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_progressbar = QtWidgets.QLabel(self.frame_progressbar)
        self.label_progressbar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progressbar.setWordWrap(True)
        self.label_progressbar.setObjectName("label_progressbar")
        self.gridLayout.addWidget(self.label_progressbar, 0, 0, 1, 2)
        self.frame_container_progressbar = QtWidgets.QFrame(self.frame_progressbar)
        self.frame_container_progressbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_container_progressbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_container_progressbar.setObjectName("frame_container_progressbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_container_progressbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.frame_container_progressbar)
        self.progressBar.setMinimumSize(QtCore.QSize(30, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.gridLayout.addWidget(self.frame_container_progressbar, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.frame_progressbar, 0, 0, 1, 1)
        self.value_label = QtWidgets.QLabel(Form)
        self.value_label.setText("")
        self.value_label.setAlignment(QtCore.Qt.AlignCenter)
        self.value_label.setObjectName("value_label")
        self.gridLayout_2.addWidget(self.value_label, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_progressbar.setText(_translate("Form", "progress bar - 1"))
